version = "1"

# Dir structure:

# /backup
#   /restic_backup
#   /aegis_backup
#   /llaves_backup


[root]
inherit="default"

[root.backup]
schedule = "*:0/5"
schedule-permission = "system"
schedule-lock-wait = "45m"
schedule-after-network-online = true

[groups]
full-backup = ["cloud", "internal"]
longer-backups = ["internal"]

{{ $sourceDir := "/run/media/ailac22/dades" }}
{{ $destCloudDir := "pcloud:backup" }}
{{ $destLocalDir := "/run/media/ailac22/seg_dades/backup" }}
{{ $resticBackupFolder := "/restic_backup"}}

[default]
systemd-drop-in-files = ["systemd-things.conf"]
# password-file = "restic-repo-password"
# password-command = "python get-restic-pass.py {{ .Profile.Name }}"
run-before = "python {{ .ConfigDir }}/run-before.py {{ .Profile.Name }} {{ .ConfigDir }}"

[default.backup]
verbose = true
source = "{{ $sourceDir }}"
# schedule = "4d" 
# dry-run = true
exclude = ["node_modules", ".Trash-1000"]
default-group = "full-backup"
# schedule = "*:0/20"
#  schedule = "*:0/5"
tag = ["dades_pc_principal"]
schedule-permission = "user"
schedule-lock-wait = "45m"
schedule-after-network-online = true

[default.forget]
keep-last = 7
keep-daily = 7
keep-weekly = 4
keep-monthly = 6
keep-yearly = 3
keep-within = "1y"
prune = true

[schedule-longer]
inherit = "default"

[schedule-longer.backup]
schedule = "weekly"

[cloud]
inherit = "default"
lock = "/tmp/resticprofile-cloud.lock"
after-backup = true
repository = "rclone:{{ $destCloudDir }}{{ $resticBackupFolder }}"
run-after = "python {{ .ConfigDir }}/run-after.py {{ $sourceDir }} {{ $destCloudDir }} {{ $destCloudDir }}"

[cloud.backup]
schedule = "daily"
schedule-permission = "user"
schedule-lock-wait = "45m"
schedule-after-network-online = true

[internal]
inherit = "schedule-longer"
lock = "/tmp/resticprofile-internal.lock"
after-backup = true
repository = "local:{{ $destLocalDir }}{{ $resticBackupFolder }}"
run-after = "python {{ .ConfigDir }}/run-after.py {{ $sourceDir }} {{ $destLocalDir }} {{ $destCloudDir }}"

[internal.backup]
schedule-permission = "user"
